---
- name: install openssh-server packages
  apt: pkg={{ item }} state=present
  with_items:
    - openssh-server

- name: create openssh-server configuration
  copy: >
    src=sshd_config dest=/etc/ssh/sshd_config
    owner=root group=root mode=0644
  notify:
    - restart openssh-server

- name: ensure openssh-server is running
  service: name=ssh state=started enabled=yes
